---
# language: the choices are (uncomment exactly one)
#   java, swift, script or c#
#language: java
#language: swift
language: script
#language: c#

# files: list your source file(s) and do not use tabs in this file.
#   Each file must be preceeded by a hyphen and indented two spaces.
#   It is safest to enclose the filename in "double quotes".
files: 
  #- "HelloWorldJava/HelloWorld.java"
  #- "hello.swift"
  #- "HelloWorldC#/hello.cs"
  - "hello.sh"
